In [2]:
import duckdb, numpy
con = duckdb.connect(database=':memory:')
def q(query: str):
    return con.execute(query).df()

In [2]:
q('''
describe '../traces/cf/**/*.parquet'
''')

   column_name column_type null   key default extra
0    timestamp      BIGINT  YES  None    None  None
1          key     VARCHAR  YES  None    None  None
2         zone     VARCHAR  YES  None    None  None
3         size      BIGINT  YES  None    None  None
4  expiry_time      BIGINT  YES  None    None  None
5   stale_time      BIGINT  YES  None    None  None
6       method      BIGINT  YES  None    None  None
7         mime     VARCHAR  YES  None    None  None
8     filename     VARCHAR  YES  None    None  None
9       server     VARCHAR  YES  None    None  None

In [23]:
df = q('''
select count(*) as n, mime
from '../traces/cf/**/*.parquet'
group by mime
having n > 100000
order by n desc
  ''')
df.head(50)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

            n                                        mime
0   572079476                                  image/webp
1   529254810                                  image/jpeg
2   481201043                            application/json
3   441999954                                   video/mp4
4   419939323                      application/javascript
5   231570333                             text/javascript
6   216910598                                   image/png
7   172585674                                    text/css
8   129034251                    application/octet-stream
9    85516571                                        None
10   83983777                                  image/avif
11   78413836                       application/x-mpegurl
12   74859460                               image/svg+xml
13   69249180                                  text/plain
14   62534761               application/vnd.apple.mpegurl
15   53094662                                   text/html
16   28698196                                  video/mp2t
17   21696415                                         */*
18   19723489                                  font/woff2
19   19537649                    application/x-javascript
20   17867012                                   image/gif
21   17002429                   application/ocsp-response
22   12817932                         binary/octet-stream
23   10504243                                   image/jxl
24   10308863                                  audio/mpeg
25    9354522                                   image/jpg
26    9299273                             application/zip
27    6104472                                image/x-icon
28    5844631                 text/vnd.trolltech.linguist
29    4431884                        application/x-binary
30    2651636                                  video/m2ts
31    2565200                             application/xml
32    2564910                 model/x-imvu-animation+marm
33    2489749                                   font/woff
34    1751761                                    font/ttf
35    1499643                        text/vnd.qt.linguist
36    1473277                      application/font-woff2
37    1447631                                    text/vtt
38    1270400                                image/x-pict
39    1223047                                       image
40    1213897                                  video/webm
41    1212865  application/private-token-issuer-directory
42    1064929                    application/vnd.api+json
43    1059807                                image/x-etc2
44     999695         application/vnd.npm.install-v1+json
45     993793                    image/vnd.microsoft.icon
46     793733                        multipart/byteranges
47     792702                                   audio/ogg
48     748136                           video/iso.segment
49     717615                      application/x-protobuf

In [21]:
q('''
select count(*) as n, cdn_content_type_id as mime
from '../traces/fb23/**/*.parquet'
group by mime
order by n desc
  ''')

           n mime
0   34441946    2
1   32361783   28
2   31714622    6
3   28556897    7
4   25725909   15
5   22030531    1
6   20096848    3
7   15449787   16
8   10206527    9
9    8701721   10
10   4780454   24
11   4276360    4
12   3572248    5
13   2353104   29
14   2198024   19
15    953819   21
16    839093    8
17    654956   13
18     80921    -
19     56970   12
20      5404    0
21      4727   25
22      2076   26
23        14   23
24         4   34
25         3   30